id: I3434A94C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:29:12+00:00'
last_modified: '2022-06-07T18:43:57.614606+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC380
  title: 'དཔལ་དེ་ཁོ་ན་ཉིད་འདུས་པའི་སྙིང་པོ་ཆོས་སྤྱོད་རབ་ཏུ་གསལ་བའི་སྙེ་མ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AA42:
      image_group_id: I2PD18348
      title: ''
      total_pages: 474
      order: 1
      base_file: AA42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
